### ISSUE TITLE
Bad TRB spot price encoding saver

### ISSUE THREAD

**Issue by tkernell** [tellor-io/polygonGovernance#22]
- Tellor360's submitValue function depends on a 12 hour old TRB SpotPrice. It uses `abi.decode(value, (uint256))` to decode the bytes value into uint256. 
- If the value is not encoded correctly, abi.decode will fail, and the whole submitValue function will fail (as well as all other function which depend on decoding the TRB price). If someone submits an incorrectly encoded TRB price which somehow doesn't get disputed within 12 hours, the oracle will be stuck forever. Someone would likely dispute this value, but it may be good to have a backup solution just in case. 
 
A possible solution: 
- add a getter function `safetyGetter(timestamp)` to flex which retrieves a specific TRB spot price and decodes it
- add a `badEncodingSaver` function to governance which uses `try/catch` to call the `safetyGetter` function. If this fails, first remove the bad value, and then use `try/catch` again to slash the reporter. We'll have to do something with the slashed stake. Give it to the caller?

**Comment by themandalore** [comment]
You should just add a try catch in 360 no?

**Comment by themandalore** [comment]
I think we can just store a previous value , and then update it if it's good, but don't if the try/catch fails.  You can also maybe add limits too...so must be >0.01 and <1,000,000 dollars or something like that

**Comment by tkernell** [comment]
yeah i think that could work. so instead of updating the stakeAmount with every submitValue, slashReporter, etc., the stakeAmount gets updated manually by a separate function. those limits are a good idea too

**Comment by tkernell** [comment]
fixed https://github.com/tellor-io/tellorFlex/pull/44
